// we decided to store this data as a js object instead of converting it from JSON
var lifespanData = [
    
    {name: "aaron", lifespan_start: "BC 121", lifespan_end: "BC 55"},
    {name: "abinadi", lifespan_start: "BC 200", lifespan_end: "BC 148"},
    {name: "abinadom", lifespan_start: "BC 270", lifespan_end: "BC 180"},
    {name: "akish", lifespan_start: "BC 1760", lifespan_end: "BC 1680"},
    {name: "alma", lifespan_start: "BC 174", lifespan_end: "BC 92"},
    {name: "alma2", lifespan_start: "BC 146", lifespan_end: "BC 73"},
    {name: "amaleki", lifespan_start: "BC 210", lifespan_end: "BC 138"},
    {name: "amalickiah", lifespan_start: "BC 110", lifespan_end: "BC 66"},
    {name: "amaron", lifespan_start: "BC 350", lifespan_end: "BC 277"},
    {name: "aminadab", lifespan_start: "BC 60", lifespan_end: "AD 10"},
    {name: "ammaron", lifespan_start: "AD 250", lifespan_end: "AD 321"},
    {name: "ammon1", lifespan_start: "BC 160", lifespan_end: "BC 90"},
    {name: "ammon2", lifespan_start: "BC 124", lifespan_end: "BC 50"},
    {name: "ammoron", lifespan_start: "BC 105", lifespan_end: "BC 61"},
    {name: "amulek", lifespan_start: "BC 140", lifespan_end: "BC 60"},
    {name: "amalekite", lifespan_start: "BC 140", lifespan_end: "BC 80"},
    {name: "angels", lifespan_start: "None", lifespan_end: "None"},
    {name: "anti-nephi-lehi", lifespan_start: "BC 120", lifespan_end: "BC 40"},
    {name: "antionah", lifespan_start: "BC 130", lifespan_end: "BC 81"},
    {name: "benjamin", lifespan_start: "BC 189", lifespan_end: "BC 119"},
    {name: "jared-brother", lifespan_start: "BC 2250", lifespan_end: "BC 2100"},
    {name: "chemish", lifespan_start: "BC 330", lifespan_end: "BC 250"},
    {name: "judge", lifespan_start: "BC 120", lifespan_end: "BC 81"},
    {name: "christ", lifespan_start: "None", lifespan_end: "None"},
    {name: "jared-daughter", lifespan_start: "BC 1730", lifespan_end: "BC 1680"},
    {name: "ishmael-daughter", lifespan_start: "BC 620", lifespan_end: "BC 540"},
    {name: "enos", lifespan_start: "BC 515", lifespan_end: "BC 417"},
    {name: "ether", lifespan_start: "BC 670", lifespan_end: "BC 600"},
    {name: "gid", lifespan_start: "BC 120", lifespan_end: "BC 40"},
    {name: "giddianhi", lifespan_start: "BC 20", lifespan_end: "AD 19"},
    {name: "giddonah", lifespan_start: "BC 160", lifespan_end: "BC 81"},
    {name: "gideon", lifespan_start: "BC 170", lifespan_end: "BC 91"},
    {name: "gidgiddoni", lifespan_start: "BC 40", lifespan_end: "AD 30"},
    {name: "godhead", lifespan_start: "None", lifespan_end: "None"},
    {name: "helaman1", lifespan_start: "BC 125", lifespan_end: "BC 57"},
    {name: "helaman2", lifespan_start: "BC 76", lifespan_end: "BC 39"},
    {name: "isaiah", lifespan_start: "BC 770", lifespan_end: "BC 680"},
    {name: "jacob-israel", lifespan_start: "BC 1830", lifespan_end: "BC 1685"},
    {name: "jacob", lifespan_start: "BC 592", lifespan_end: "BC 495"},
    {name: "jared", lifespan_start: "BC 2250", lifespan_end: "BC 2100"},
    {name: "jared2", lifespan_start: "BC 1750", lifespan_end: "BC 1680"},
    {name: "jarom", lifespan_start: "BC 440", lifespan_end: "BC 355"},
    {name: "john", lifespan_start: "BC 5", lifespan_end: "AD 30"},
    {name: "joseph", lifespan_start: "BC 1740", lifespan_end: "BC 1630"},
    {name: "joshua", lifespan_start: "BC 1355", lifespan_end: "BC 1245"},
    {name: "korihor", lifespan_start: "BC 120", lifespan_end: "BC 74"},
    {name: "laban", lifespan_start: "BC 650", lifespan_end: "BC 600"},
    {name: "lachoneus", lifespan_start: "BC 50", lifespan_end: "AD 31"},
    {name: "laman-spy", lifespan_start: "BC 100", lifespan_end: "BC 30"},
    {name: "lamanite-king", lifespan_start: "BC 200", lifespan_end: "BC 130"},
    {name: "lamoni-wife", lifespan_start: "BC 130", lifespan_end: "BC 60"},
    {name: "lamoni", lifespan_start: "BC 130", lifespan_end: "BC 60"},
    {name: "lamoni-father", lifespan_start: "BC 160", lifespan_end: "BC 85"},
    {name: "lehi", lifespan_start: "BC 650", lifespan_end: "BC 570"},
    {name: "limhi", lifespan_start: "BC 170", lifespan_end: "BC 90"},
    {name: "malachi", lifespan_start: "BC 490", lifespan_end: "BC 450"},
    {name: "micah", lifespan_start: "BC 740", lifespan_end: "BC 690"},
    {name: "mormon", lifespan_start: "AD 311", lifespan_end: "AD 390"},
    {name: "moroni1", lifespan_start: "BC 110", lifespan_end: "BC 56"},
    {name: "moroni2", lifespan_start: "AD 340", lifespan_end: "AD 425"},
    {name: "moses", lifespan_start: "BC 1391", lifespan_end: "BC 1271"},
    {name: "mosiah", lifespan_start: "BC 154", lifespan_end: "BC 91"},
    {name: "nephi1", lifespan_start: "BC 615", lifespan_end: "BC 540"},
    {name: "nephi2", lifespan_start: "BC 54", lifespan_end: "BC 1"},
    {name: "nephihah", lifespan_start: "BC 155", lifespan_end: "BC 67"},
    {name: "nephi-brethren", lifespan_start: "BC 620", lifespan_end: "BC 540"},
    {name: "noah", lifespan_start: "BC 195", lifespan_end: "BC 148"},
    {name: "omni", lifespan_start: "BC 390", lifespan_end: "BC 315"},
    {name: "pahoran", lifespan_start: "BC 125", lifespan_end: "BC 52"},
    {name: "poor-zoramite", lifespan_start: "BC 120", lifespan_end: "BC 50"},
    {name: "samuel-lamanite", lifespan_start: "BC 55", lifespan_end: "AD 25"},
    {name: "sariah", lifespan_start: "BC 650", lifespan_end: "BC 570"},
    {name: "satan", lifespan_start: "None", lifespan_end: "None"},
    {name: "helaman-servant", lifespan_start: "BC 85", lifespan_end: "BC 5"},
    {name: "lamoni-servant", lifespan_start: "BC 120", lifespan_end: "BC 50"},
    {name: "sherem", lifespan_start: "BC 550", lifespan_end: "BC 500"},
    {name: "nephite-soldier", lifespan_start: "BC 105", lifespan_end: "BC 25"},
    {name: "zeezrom", lifespan_start: "BC 130", lifespan_end: "BC 50"},
    {name: "zeniff", lifespan_start: "BC 240", lifespan_end: "BC 160"},
    {name: "zenock", lifespan_start: "BC 700", lifespan_end: "BC 650"},
    {name: "zenos", lifespan_start: "BC 700", lifespan_end: "BC 620"},
    {name: "zerahemnah", lifespan_start: "BC 105", lifespan_end: "BC 25"},
    {name: "zoramite-prayer", lifespan_start: "None", lifespan_end: "None"}
    ]
    
