var timelineData = [
    {
        chronological: 0,
        name: "jared-brother",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 1,
        name: "shule",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 2,
        name: "omer",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 3,
        name: "jared",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 4,
        name: "jared-daughter",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 5,
        name: "akish",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 6,
        name: "morianton",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 7,
        name: "morianton-servant",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 8,
        name: "lib1",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 9,
        name: "ether",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 10,
        name: "coriantumr",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 11,
        name: "gilead",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 12,
        name: "lib2",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 13,
        name: "shiz",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 14,
        name: "lehi",
        incoming: [],
        outgoing: ["nephi1", "enos", "christ", "mormon"],
    },
    {
        chronological: 15,
        name: "sariah",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 16,
        name: "nephi1",
        incoming: ["lehi"],
        outgoing: ["enos", "mormon", "zeniff", "abinadi", "christ"],
    },
    {
        chronological: 17,
        name: "laman",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 18,
        name: "lemuel",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 19,
        name: "laban",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 20,
        name: "zoram",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 21,
        name: "ishmael",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 22,
        name: "jacob",
        incoming: [],
        outgoing: ["enos", "mormon"],
    },
    {
        chronological: 23,
        name: "sherem",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 24,
        name: "enos",
        incoming: [ "lehi", "nephi1", "jacob"],
        outgoing: ["mormon"],
    },
    // {
    //     chronological: 100, // wrong
    //     name: "jarom",
    //     incoming: [],
    //     outgoing: [],
    // },

    {
        chronological: 26,
        name: "benjamin",
        incoming: ["abinadi"],
        outgoing: ["mormon"],
    },    
    {
        chronological: 25,
        name: "mosiah",
        incoming: [],
        outgoing: ["abinadi", "mormon"],
    },
    {
        chronological: 27,
        name: "zeniff",
        incoming: ["nephi1"],
        outgoing: ["mormon"],
    },
    // {
    //     chronological: 28,
    //     name: "laman",
    //     incoming: [],
    //     outgoing: [],
    // },
    {
        chronological: 29,
        name: "noah",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 30,
        name: "abinadi",
        incoming: ["nephi1", "mosiah",],
        outgoing: [ "benjamin", "alma", "alma2", "amulek", "nephi2", "samuel-lamanite", "christ", "mormon", "moroni2", ],
    },
    {
        chronological: 31,
        name: "alma",
        incoming: ["abinadi"],
        outgoing: [],
    },
    {
        chronological: 32,
        name: "gideon",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 33,
        name: "amulon",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 34,
        name: "alma2",
        incoming: ["abinadi"],
        outgoing: ["korihor", "mormon"],
    },
    {
        chronological: 35,
        name: "nehor",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 36,
        name: "ammon2",
        incoming: [],
        outgoing: ["lamoni", "mormon"],
    },
    {
        chronological: 37,
        name: "aaron",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 38,
        name: "omner-himni",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 39,
        name: "amlici",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 40,
        name: "amnor",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 41,
        name: "limher",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 42,
        name: "manti",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 43,
        name: "zeram",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 44,
        name: "amulek",
        incoming: ["abinadi"],
        outgoing: ["mormon"],
    },
    {
        chronological: 45,
        name: "zeezrom",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 46,
        name: "nephite-daughter",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 47,
        name: "lamoni",
        incoming: ["ammon2"],
        outgoing: ["lamoni-father"],
    },
    {
        chronological: 48,
        name: "lamoni-father",
        incoming: ["lamoni"],
        outgoing: ["mormon"],
    },
    {
        chronological: 49,
        name: "abish",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 50,
        name: "korihor",
        incoming: ["alma2"],
        outgoing: ["christ"],
    },
    {
        chronological: 51,
        name: "moroni1",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 52,
        name: "zerahemnah",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 53,
        name: "amalickiah",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 54,
        name: "lehonti",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 55,
        name: "teancum",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 56,
        name: "pahoran",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 57,
        name: "lehi2",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 58,
        name: "ammoron",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 59,
        name: "laman-spy",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 60,
        name: "jacob-apostate",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 61,
        name: "pachus",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 62,
        name: "helaman1",
        incoming: [],
        outgoing: ["mormon"],
    },
    {
        chronological: 63,
        name: "paanchi",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 64,
        name: "kishkumen",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 65,
        name: "moronihah",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 66,
        name: "coriantumr2",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 67,
        name: "gadianton",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 68,
        name: "nephi2",
        incoming: ["abinadi"],
        outgoing: ["christ"],
    },
    {
        chronological: 69,
        name: "seezoram",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 70,
        name: "seantum",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 71,
        name: "samuel-lamanite",
        incoming: ["abinadi"],
        outgoing: ["mormon"],
    },
    {
        chronological: 72,
        name: "giddianhi",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 73,
        name: "zemnarihah",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 74,
        name: "gidgiddoni",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 75,
        name: "christ",
        incoming: ["lehi", "nephi1", "jacob", "abinadi", "alma2", "korihor", "moroni1", "nephi2", "samuel-lamanite"],
        outgoing: ["mormon"],
    },
    {
        chronological: 76,
        name: "ammaron",
        incoming: [],
        outgoing: [],
    },
    {
        chronological: 77,
        name: "mormon",
        incoming: ["lehi", "nephi1", "jacob", "enos", "zeniff", "benjamin", "mosiah", "abinadi", "alma2", "ammon2", "amulek", "lamoni-father", "helaman1", "samuel-lamanite", "christ"],
        outgoing: ["moroni2"],
    },
    {
        chronological: 78,
        name: "moroni2",
        incoming: [ "abinadi", "mormon",],
        outgoing: [],
    },
    ]

    const idNames = [
        "aaron",
        "abinadi",
        "abinadom",
        "akish",
        "alma",
        "alma2",
        "amaleki",
        "amalickiah",
        "amaron",
        "aminadab",
        "ammaron",
        "ammon1",
        "ammon2",
        "ammoron",
        "amulek",
        "amalekite",
        "angels",
        "anti-nephi-lehi",
        "antionah",
        "benjamin",
        "jared-brother",
        "moroni1",
        "chemish",
        "judge",
        "christ",
        "jared-daughter",
        "omer",
        "ishmael-daughter",
        "enos",
        "ether",
        "gid",
        "giddianhi",
        "giddonah",
        "gideon",
        "gidgiddoni",
        "godhead",
        "helaman1",
        "helaman2",
        "isaiah",
        "jacob-israel",
        "jacob",
        "jared2",
        "jared1",
        "jarom",
        "john",
        "joseph",
        "joshua",
        "korihor",
        "laban",
        "lachoneus",
        "laman-spy",
        "lamanite-king",
        "lamoni",
        "lamoni-father",
        "lamoni-wife",
        "lehi",
        "limhi",
        "malachi",
        "micah",
        "mormon",
        "moroni2",
        "moses",
        "mosiah",
        "nephi2",
        "nephi1",
        "nephihah",
        "nephi-brethren",
        "nephite-soldier",
        "noah",
        "omni",
        "pahoran",
        "poor-zoramite",
        "samuel-lamanite",
        "sariah",
        "satan",
        "helaman-servant",
        "lamoni-servant",
        "sherem",
        "zeezrom",
        "zeniff",
        "zenock",
        "zenos",
        "zerahemnah",
        "zoramite-prayer",
    ]
    
    const displayNames = [
        "Aaron",
        "Abinadi",
        "Abinadom",
        "Akish",
        "Alma",
        "Alma the Younger",
        "Amaleki",
        "Amalickiah",
        "Amaron",
        "Aminadab",
        "Ammaron",
        "Ammon the Mulekite",
        "Ammon",
        "Ammoron",
        "Amulek",
        "An Amalekite",
        "Angels",
        "Anti-Nephi-Lehi",
        "Antionah",
        "Benjamin",
        "Brother of Jared",
        "Captain Moroni",
        "Chemish",
        "Chief Judge",
        "Christ in America",
        "Daughter of Jared Son of Omer",
        "Omer",
        "Daughters of Ishmael",
        "Enos",
        "Ether",
        "Gid",
        "Giddianhi",
        "Giddonah",
        "Gideon",
        "Gidgiddoni",
        "Godhead",
        "Helaman",
        "Helaman Son of Helaman",
        "Isaiah",
        "Jacob (Israel)",
        "Jacob",
        "Jared",
        "Jared Son of Omer",
        "Jarom",
        "John the Baptist",
        "Joseph",
        "Joshua",
        "Korihor",
        "Laban",
        "Lachoneus",
        "Laman the Nephite Spy",
        "Lamanite King",
        "Lamoni",
        "Lamoni's Father",
        "Lamoni's Wife",
        "Lehi",
        "Limhi",
        "Malachi",
        "Micah",
        "Mormon",
        "Moroni",
        "Moses",
        "Mosiah",
        "Nephi Son of Helaman",
        "Nephi",
        "Nephihah",
        "Nephi's Brethren",
        "Nephite Soldier",
        "Noah",
        "Omni",
        "Pahoran",
        "Poor Zoramite",
        "Samuel the Lamanite",
        "Sariah",
        "Satan",
        "Servant of Helaman",
        "Servant of Lamoni",
        "Sherem",
        "Zeezrom",
        "Zeniff",
        "Zenock",
        "Zenos",
        "Zerahemnah",
        "Zoramite Prayer"
    ];
    
    function getDisplayName(idName) {
        return displayNames[idNames.indexOf(idName)];
    }
    