function importData() {
    const url = './compiledDataNew.json'; // local Server
    const req = new XMLHttpRequest();
    // console.log(url)
    
    req.open("GET", url, false);
    req.send(null);
    return JSON.parse(req.response);
}

const dataAll = importData();

function getImageString(name) {
    // return './images/' + name + '.jpg' // for local
    return './images/' + name + '.jpg' // for server
}




const idNames = [
    "aaron",
    "abinadi",
    "abinadom",
    "akish",
    "alma",
    "alma2",
    "amaleki",
    "amalickiah",
    "amaron",
    "aminadab",
    "ammaron",
    "ammon2",
    "ammon1",
    "ammoron",
    "amulek",
    "amalekite",
    "angels",
    "anti-nephi-lehi",
    "antionah",
    "benjamin",
    "jared-brother",
    "moroni1",
    "chemish",
    "judge",
    "christ",
    "jared-daughter",
    "omer",
    "ishmael-daughter",
    "enos",
    "ether",
    "gid",
    "giddianhi",
    "giddonah",
    "gideon",
    "gidgiddoni",
    "godhead",
    "helaman1",
    "helaman2",
    "isaiah",
    "jacob-israel",
    "jacob",
    "jared2",
    "jared1",
    "jarom",
    "john",
    "joseph",
    "joshua",
    "korihor",
    "laban",
    "lachoneus",
    "laman-spy",
    "lamanite-king",
    "lamoni",
    "lamoni-father",
    "lamoni-wife",
    "lehi",
    "limhi",
    "malachi",
    "micah",
    "mormon",
    "moroni2",
    "moses",
    "mosiah",
    "nephi2",
    "nephi1",
    "nephihah",
    "nephi-brethren",
    "nephite-soldier",
    "noah",
    "omni",
    "pahoran",
    "poor-zoramite",
    "samuel-lamanite",
    "sariah",
    "satan",
    "helaman-servant",
    "lamoni-servant",
    "sherem",
    "zeezrom",
    "zeniff",
    "zenock",
    "zenos",
    "zerahemnah",
    "zoramite-prayer",
]

const displayNames = [
    "Aaron",
    "Abinadi",
    "Abinadom",
    "Akish",
    "Alma",
    "Alma the Younger",
    "Amaleki",
    "Amalickiah",
    "Amaron",
    "Aminadab",
    "Ammaron",
    "Ammon",
    "Ammon the Mulekite",
    "Ammoron",
    "Amulek",
    "An Amalekite",
    "Angels",
    "Anti-Nephi-Lehi",
    "Antionah",
    "Benjamin",
    "Brother of Jared",
    "Captain Moroni",
    "Chemish",
    "Chief Judge",
    "Christ in America",
    "Daughter of Jared Son of Omer",
    "Omer",
    "Daughters of Ishmael",
    "Enos",
    "Ether",
    "Gid",
    "Giddianhi",
    "Giddonah",
    "Gideon",
    "Gidgiddoni",
    "Godhead",
    "Helaman",
    "Helaman Son of Helaman",
    "Isaiah",
    "Jacob (Israel)",
    "Jacob",
    "Jared Son of Omer",
    "Jared",
    "Jarom",
    "John the Baptist",
    "Joseph",
    "Joshua",
    "Korihor",
    "Laban",
    "Lachoneus",
    "Laman the Nephite Spy",
    "Lamanite King",
    "Lamoni",
    "Lamoni's Father",
    "Lamoni's Wife",
    "Lehi",
    "Limhi",
    "Malachi",
    "Micah",
    "Mormon",
    "Moroni",
    "Moses",
    "Mosiah",
    "Nephi Son of Helaman",
    "Nephi",
    "Nephihah",
    "Nephi's Brethren",
    "Nephite Soldier",
    "Noah",
    "Omni",
    "Pahoran",
    "Poor Zoramite",
    "Samuel the Lamanite",
    "Sariah",
    "Satan",
    "Servant of Helaman",
    "Servant of Lamoni",
    "Sherem",
    "Zeezrom",
    "Zeniff",
    "Zenock",
    "Zenos",
    "Zerahemnah",
    "Zoramite Prayer"
];

function getDisplayName(id) {
    return displayNames[idNames.indexOf(id)]
}

function testIdToDisplayFunction() {
    for (let name of idNames) {
        console.log({
            id: name,
            display: getDisplayName(name)
        })
    }
}
// testIdToDisplayFunction();

const group_major = [
    "lehi",
    "nephi1",
    "jacob",
    "enos",
    "jarom",
    "zeniff",
    "amaleki",
    "abinadi",
    "benjamin",
    "alma",
    "limhi",
    "mosiah",
    "amulek",
    "alma2",
    "ammon2",
    "korihor",
    "pahoran",
    "moroni1",
    "helaman1",
    "nephi2",
    "samuel-lamanite",
    "mormon",
    "moroni2",
]

const group_secondary = [
    "sariah",
    "nephi-brethren",
    "omni",
    "chemish",
    "noah",
    "lamoni-father",
    "anti-nephi-lehi",
    "lamoni",
    "aaron",
    "zeezrom",
    "helaman2",
    "giddianhi",
]

const group_minimal = [
    "laban", 
    "ishmael-daughter",
    "sherem",
    "amaron",
    "abinadom", 
    "lamanite-king",
    "gideon",
    "giddonah",
    "ammon1",
    "nephihah",
    "amalekite",
    "lamoni-wife",
    "antionah",
    "lamoni-servant", 
    "judge",
    "gid",
    "amalickiah",
    "zerahemnah",
    "ammaron",
    "nephite-soldier",
    "laman-spy",
    "aminadab",
    "lachoneus",
    "gidgiddoni",
    "poor-zoramite",
    "abinadom",
    "zoramite-prayer",
    "ammoron",
    "helaman1", 
]

const group_jaredites = [
    "akish",
    "jared-brother",
    "jared2",
    "jared-daughter",
    "jared1",
    "ether",
]

const group_OT = [
    "joshua",
    "zenock",
    "john",
    "satan",
    "jacob-israel",
    "micah",
    "moses",
    "malachi",
    "joseph",
    "angels",
    "zenos",
    "christ",
    "godhead",
    "isaiah",
]
