const idNames = [
    "aaron",
    "abinadi",
    "abinadom",
    "akish",
    "alma",
    "alma2",
    "amaleki",
    "amalickiah",
    "amaron",
    "aminadab",
    "ammaron",
    "ammon2",
    "ammon1",
    "ammoron",
    "amulek",
    "amalekite",
    "angels",
    "anti-nephi-lehi",
    "antionah",
    "benjamin",
    "jared-brother",
    "moroni1",
    "chemish",
    "judge",
    "christ",
    "jared-daughter",
    // "omer",
    "ishmael-daughter",
    "enos",
    "ether",
    "gid",
    "giddianhi",
    "giddonah",
    "gideon",
    "gidgiddoni",
    "godhead",
    "helaman1",
    "helaman2",
    "isaiah",
    // "jacob-israel",
    "jacob",
    "jared2",
    "jared1",
    "jarom",
    "john",
    "joseph",
    "joshua",
    "korihor",
    "laban",
    "lachoneus",
    "laman-spy",
    "lamanite-king",
    "lamoni",
    // "lamoni-father",
    "lamoni-wife",
    "lehi",
    "limhi",
    "malachi",
    "micah",
    "mormon",
    "moroni2",
    "moses",
    "mosiah",
    "nephi2",
    "nephi1",
    "nephihah",
    // "nephi-brethren",
    "nephite-soldier",
    "noah",
    "omni",
    "pahoran",
    "poor-zoramite",
    "samuel-lamanite",
    "sariah",
    "satan",
    "helaman-servant",
    "lamoni-servant",
    "sherem",
    "zeezrom",
    "zeniff",
    "zenock",
    "zenos",
    "zerahemnah",
    "zoramite-prayer",
]

const displayNames = [
    "Aaron",
    "Abinadi",
    "Abinadom",
    "Akish",
    "Alma",
    "Alma the Younger",
    "Amaleki",
    "Amalickiah",
    "Amaron",
    "Aminadab",
    "Ammaron",
    "Ammon",
    "Ammon the Mulekite",
    "Ammoron",
    "Amulek",
    "An Amalekite",
    "Angels",
    "Anti-Nephi-Lehi",
    "Antionah",
    "Benjamin",
    "Brother of Jared",
    "Captain Moroni",
    "Chemish",
    "Chief Judge",
    "Christ in America",
    "Daughter of Jared Son of Omer",
    // "Omer",
    "Daughters of Ishmael",
    "Enos",
    "Ether",
    "Gid",
    "Giddianhi",
    "Giddonah",
    "Gideon",
    "Gidgiddoni",
    "Godhead",
    "Helaman",
    "Helaman Son of Helaman",
    "Isaiah",
    // "Jacob (Israel)",
    "Jacob",
    "Jared",
    "Jared Son of Omer",
    "Jarom",
    "John the Baptist",
    "Joseph",
    "Joshua",
    "Korihor",
    "Laban",
    "Lachoneus",
    "Laman the Nephite Spy",
    "Lamanite King",
    "Lamoni",
    // "Lamoni's Father",
    "Lamoni's Wife",
    "Lehi",
    "Limhi",
    "Malachi",
    "Micah",
    "Mormon",
    "Moroni",
    "Moses",
    "Mosiah",
    "Nephi Son of Helaman",
    "Nephi",
    "Nephihah",
    // "Nephi's Brethren",
    "Nephite Soldier",
    "Noah",
    "Omni",
    "Pahoran",
    "Poor Zoramite",
    "Samuel the Lamanite",
    "Sariah",
    "Satan",
    "Servant of Helaman",
    "Servant of Lamoni",
    "Sherem",
    "Zeezrom",
    "Zeniff",
    "Zenock",
    "Zenos",
    "Zerahemnah",
    "Zoramite Prayer"
];

const init = () => {
    const urlParams = new URLSearchParams(window.location.search);
    var speaker = urlParams.get('speaker');
    
    // let pathArray = window.location.pathname.substr(1).split("/");
    // speaker = pathArray[2];
    console.log(speaker);
    if (speaker && idNames.includes(speaker)) {
    //    loadNewDataset(speaker);
    }

    return;
}

init();

function idNameToDisplayName(idName) {
    return displayNames[idNames.indexOf(idName)];
}


// // check alignment of id names and display names
// for (id of idNames) {
//     console.log(id, idNameToDisplayName(id));
// }